// Copyright (c) 2016 Jack Grigg
// Copyright (c) 2016 The Zcash developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php .

#if defined(HAVE_CONFIG_H)
#include "config/bitcoin-config.h"
#endif

#include "arith_uint256.h"
#include "chainparams.h"
#include "crypto/sha256.h"
#include "crypto/equihash.h"
#ifdef ENABLE_MINING
#include "pow/tromp/equi_miner.h"
#endif
#include "pow.h"
#include "primitives/block.h"
#include "streams.h"
#include "test/test_bitcoin.h"
#include "uint256.h"
#include "utilstrencodings.h"
#include "utiltime.h"
#include "version.h"

#include "sodium.h"

#include <stdexcept>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <set>
#include <string>
#include <vector>

#include <boost/test/unit_test.hpp>

BOOST_FIXTURE_TEST_SUITE(equihash_tests, BasicTestingSetup)

/** Open a KAT file from repo root or src/test/data/ (cwd: root, src/, src/test/). */
static bool OpenKatFile(const char* basename, std::ifstream& in)
{
    const std::string candidates[] = {
        basename,
        std::string("src/test/data/") + basename,
        std::string("../src/test/data/") + basename,
        std::string("../../src/test/data/") + basename,
        std::string("../") + basename,
        std::string("../../") + basename,
    };
    for (const std::string& p : candidates) {
        in.close();
        in.clear();
        in.open(p.c_str());
        if (in.good()) {
            return true;
        }
    }
    return false;
}

static std::vector<uint32_t> ParseIndicesBlock(std::istream& in)
{
    std::vector<uint32_t> idx;
    std::string line;
    while (std::getline(in, line)) {
        if (line.find("indices:") != std::string::npos) {
            break;
        }
    }
    while (std::getline(in, line)) {
        if (line.find('}') != std::string::npos) {
            // may still have numbers before }
            for (char& c : line) {
                if (c == '{' || c == '}' || c == ',') {
                    c = ' ';
                }
            }
            std::istringstream ls(line);
            uint32_t v;
            while (ls >> v) {
                idx.push_back(v);
            }
            break;
        }
        for (char& c : line) {
            if (c == '{' || c == '}' || c == ',') {
                c = ' ';
            }
        }
        std::istringstream ls(line);
        uint32_t v;
        while (ls >> v) {
            idx.push_back(v);
        }
    }
    return idx;
}

BOOST_AUTO_TEST_CASE(unsupported_equihash_params_throw) {
    eh_HashState state;
    BOOST_CHECK_THROW(EhInitialiseState(1, 1, state), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(zero_mainnet_genesis_equihash_192_7_valid) {
    SelectParams(CBaseChainParams::MAIN);
    const Consensus::Params& consensus = Params().GetConsensus();
    BOOST_CHECK_EQUAL(consensus.nEquihashN, 192u);
    BOOST_CHECK_EQUAL(consensus.nEquihashK, 7u);
    const CBlock& genesis = Params().GenesisBlock();
    CBlockHeader hdr = genesis.GetBlockHeader();
    BOOST_CHECK(CheckEquihashSolution(&hdr, consensus));
}

// One-shot dump for TST-05: run once, writes repo-root 1927EQ.txt (env DUMP_1927EQ=1).
BOOST_AUTO_TEST_CASE(dump_mainnet_genesis_192_7_indices) {
    if (getenv("DUMP_1927EQ") == nullptr) {
        return;
    }
    SelectParams(CBaseChainParams::MAIN);
    const Consensus::Params& consensus = Params().GetConsensus();
    const CBlock& genesis = Params().GenesisBlock();
    CBlockHeader hdr = genesis.GetBlockHeader();
    BOOST_REQUIRE(CheckEquihashSolution(&hdr, consensus));
    const size_t cBitLen = consensus.nEquihashN / (consensus.nEquihashK + 1);
    std::vector<eh_index> idx = GetIndicesFromMinimal(hdr.nSolution, cBitLen);
    BOOST_REQUIRE_EQUAL(idx.size(), 128u);

    const char* outPath = getenv("DUMP_1927EQ");
    std::string path = outPath && *outPath ? outPath : "1927EQ.txt";
    std::ofstream out(path.c_str());
    BOOST_REQUIRE(out.good());
    out << "# Zero mainnet Equihash (192,7) vectors for TST-05\n";
    out << "# Source: Params().GenesisBlock() header (I = CEquihashInput||nNonce)\n";
    out << "# Validate with CheckEquihashSolution / EhIsValidSolution on header state (see pow.cpp)\n";
    out << "# Generated by equihash_tests/dump_mainnet_genesis_192_7_indices\n";
    out << "\n";
    out << "params: n=192 k=7\n";
    out << "label: mainnet_genesis\n";
    out << "height: 0\n";
    out << "nNonce: " << hdr.nNonce.GetHex() << "\n";
    out << "nSolution_hex: " << HexStr(hdr.nSolution) << "\n";
    out << "cBitLen: " << cBitLen << "\n";
    out << "indices_count: " << idx.size() << "\n";
    out << "indices: {\n  ";
    for (size_t i = 0; i < idx.size(); i++) {
        if (i) out << (i % 8 == 0 ? ",\n  " : ", ");
        out << idx[i];
    }
    out << "\n}\n";
    out << "\n# Round-trip: GetMinimalFromIndices(indices, 24) must equal nSolution_hex\n";
    std::vector<unsigned char> roundtrip = GetMinimalFromIndices(idx, cBitLen);
    out << "roundtrip_ok: " << (roundtrip == hdr.nSolution ? "true" : "false") << "\n";
    out.close();
    BOOST_TEST_MESSAGE("Wrote " << path);
}

BOOST_AUTO_TEST_CASE(zero_mainnet_genesis_equihash_rejects_corrupt_solution) {
    SelectParams(CBaseChainParams::MAIN);
    CBlock genesisMut = Params().GenesisBlock();
    BOOST_REQUIRE(!genesisMut.nSolution.empty());
    genesisMut.nSolution[0] ^= 0xff;
    CBlockHeader hdr = genesisMut.GetBlockHeader();
    BOOST_CHECK(!CheckEquihashSolution(&hdr, Params().GetConsensus()));
}

BOOST_AUTO_TEST_CASE(zero_regtest_genesis_equihash_48_5_valid) {
    SelectParams(CBaseChainParams::REGTEST);
    const Consensus::Params& consensus = Params().GetConsensus();
    BOOST_CHECK_EQUAL(consensus.nEquihashN, 48u);
    BOOST_CHECK_EQUAL(consensus.nEquihashK, 5u);
    const CBlock& genesis = Params().GenesisBlock();
    CBlockHeader hdr = genesis.GetBlockHeader();
    BOOST_CHECK(CheckEquihashSolution(&hdr, consensus));
    SelectParams(CBaseChainParams::MAIN);
}

// Wire 1927EQ.txt indices <-> genesis nSolution (header form).
BOOST_AUTO_TEST_CASE(validator_testvectors_192_7) {
    SelectParams(CBaseChainParams::MAIN);
    const Consensus::Params& consensus = Params().GetConsensus();
    BOOST_REQUIRE_EQUAL(consensus.nEquihashN, 192u);
    BOOST_REQUIRE_EQUAL(consensus.nEquihashK, 7u);
    const size_t cBitLen = consensus.nEquihashN / (consensus.nEquihashK + 1);

    std::ifstream in;
    BOOST_REQUIRE_MESSAGE(OpenKatFile("1927EQ.txt", in),
                          "1927EQ.txt not found (run from repo root or src/)");
    std::vector<uint32_t> idx = ParseIndicesBlock(in);
    BOOST_REQUIRE_EQUAL(idx.size(), 128u);

    const CBlock& genesis = Params().GenesisBlock();
    std::vector<unsigned char> minimal = GetMinimalFromIndices(idx, cBitLen);
    BOOST_CHECK(minimal == genesis.nSolution);

    CBlockHeader hdr = genesis.GetBlockHeader();
    hdr.nSolution = minimal;
    BOOST_CHECK(CheckEquihashSolution(&hdr, consensus));

    // Negative: swap first pair -> invalid
    std::swap(idx[0], idx[1]);
    hdr.nSolution = GetMinimalFromIndices(idx, cBitLen);
    BOOST_CHECK(!CheckEquihashSolution(&hdr, consensus));
}

// TST-05: second mainnet (192,7) header vector -- height 1 block bytes.
BOOST_AUTO_TEST_CASE(validator_testvectors_192_7_h1) {
    SelectParams(CBaseChainParams::MAIN);
    const Consensus::Params& consensus = Params().GetConsensus();
    std::ifstream in;
    BOOST_REQUIRE_MESSAGE(OpenKatFile("1927EQ_h1.hex", in),
                          "1927EQ_h1.hex not found");
    std::string hex;
    std::getline(in, hex);
    while (!hex.empty() && (hex.back() == '\n' || hex.back() == '\r' || hex.back() == ' ')) {
        hex.pop_back();
    }
    std::vector<unsigned char> raw = ParseHex(hex);
    BOOST_REQUIRE(!raw.empty());
    CDataStream ss(raw, SER_NETWORK, PROTOCOL_VERSION);
    CBlock block;
    ss >> block;
    CBlockHeader hdr = block.GetBlockHeader();
    BOOST_CHECK(CheckEquihashSolution(&hdr, consensus));

    const size_t cBitLen = consensus.nEquihashN / (consensus.nEquihashK + 1);
    std::vector<eh_index> idx = GetIndicesFromMinimal(hdr.nSolution, cBitLen);
    BOOST_REQUIRE_EQUAL(idx.size(), 128u);
    BOOST_CHECK(GetMinimalFromIndices(idx, cBitLen) == hdr.nSolution);
}

// TST-05: regtest (48,5) genesis index round-trip (validator always on).
BOOST_AUTO_TEST_CASE(validator_testvectors_48_5) {
    SelectParams(CBaseChainParams::REGTEST);
    const Consensus::Params& consensus = Params().GetConsensus();
    BOOST_REQUIRE_EQUAL(consensus.nEquihashN, 48u);
    BOOST_REQUIRE_EQUAL(consensus.nEquihashK, 5u);
    const size_t cBitLen = consensus.nEquihashN / (consensus.nEquihashK + 1);
    CBlockHeader hdr = Params().GenesisBlock().GetBlockHeader();
    BOOST_REQUIRE(CheckEquihashSolution(&hdr, consensus));
    std::vector<eh_index> idx = GetIndicesFromMinimal(hdr.nSolution, cBitLen);
    BOOST_REQUIRE_EQUAL(idx.size(), 32u);
    BOOST_CHECK(GetMinimalFromIndices(idx, cBitLen) == hdr.nSolution);
    std::swap(idx[0], idx[1]);
    hdr.nSolution = GetMinimalFromIndices(idx, cBitLen);
    BOOST_CHECK(!CheckEquihashSolution(&hdr, consensus));
    SelectParams(CBaseChainParams::MAIN);
}

#ifdef ENABLE_MINING
// TST-05: (48,5) solver on regtest genesis header state -- finds >=1 valid solution;
// BasicSolve and OptimisedSolve agree.
// Capture the (192,7) solver's full solution set as the differential baseline
// for optimization work (contrib/perf/PerfEqu.md S3.2c).
//
// Why this exists: solver_testvectors_48_5 pins the solver only at 512 rows,
// where no memory hierarchy is exercised. At (192,7) the list is 33,554,432
// rows, so a tuning can be correct at regtest and wrong in production and pass
// every other test in this file.
//
// The CURRENT OptimisedSolve is treated as definitive: it is the deployed
// consensus miner, and any later change must reproduce its solution set
// exactly. Opt-in because one solve is ~60 s:
//
//   DUMP_1927_SOLVER=vectors.txt ./src/test/test_bitcoin \
//       --run_test=equihash_tests/solver_baseline_192_7
//
// Re-run after a change and diff the SETS (order-independent). A changed set is
// a regression even if every emitted solution still verifies -- dropping
// solutions looks like a speedup on wall-clock and is a loss in Sol/s.
BOOST_AUTO_TEST_CASE(solver_baseline_192_7) {
    const char* outPath = getenv("DUMP_1927_SOLVER");
    if (outPath == nullptr) {
        return;  // ~60 s per solve; opt-in only
    }
    SelectParams(CBaseChainParams::MAIN);
    const Consensus::Params& consensus = Params().GetConsensus();
    const unsigned int n = consensus.nEquihashN;
    const unsigned int k = consensus.nEquihashK;
    BOOST_REQUIRE_EQUAL(n, 192u);
    BOOST_REQUIRE_EQUAL(k, 7u);
    const size_t cBitLen = n / (k + 1);
    CBlockHeader hdr = Params().GenesisBlock().GetBlockHeader();

    // state built by the shared helper below
    CEquihashInput I{hdr};
    CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
    ss << I;
    ss << hdr.nNonce;
    eh_HashState state = EhPrefixState(n, k, (unsigned char*)&ss[0], ss.size());

    // Collect EVERY solution, not just the first: the set is the baseline.
    std::set<std::vector<uint32_t>> sols;
    EhOptimisedSolveUncancellable(n, k, state, [&](std::vector<unsigned char> soln) {
        sols.insert(GetIndicesFromMinimal(soln, cBitLen));
        return false;  // keep going
    });
    BOOST_REQUIRE_MESSAGE(!sols.empty(),
                          "OptimisedSolve found no (192,7) solutions on mainnet genesis");

    // Every emitted solution must independently verify -- V1 inside the vector
    // capture, so a bad baseline cannot be recorded as good.
    for (const auto& idx : sols) {
        std::vector<eh_index> ehidx(idx.begin(), idx.end());
        bool ok = false;
        // EhIsValidSolution is a macro with a `ret` out-parameter, not a
        // function; it dispatches on (n,k) to the right Equihash instance.
        EhIsValidSolution(n, k, state, GetMinimalFromIndices(ehidx, cBitLen), ok);
        BOOST_CHECK_MESSAGE(ok, "solver emitted a solution that does not verify");
    }

    std::ofstream out(outPath);
    BOOST_REQUIRE_MESSAGE(out.good(), "cannot open DUMP_1927_SOLVER path");
    out << "# Zero (192,7) solver baseline -- mainnet genesis header\n";
    out << "# Source: EhOptimisedSolve, treated as definitive (PerfEqu.md S3.2c)\n";
    out << "# Compare SETS, not order.\n";
    out << "nsols " << sols.size() << "\n";
    for (const auto& idx : sols) {
        out << "sol";
        for (uint32_t v : idx) out << " " << v;
        out << "\n";
    }
    out.close();
    BOOST_TEST_MESSAGE("wrote " << sols.size() << " (192,7) solution(s) to " << outPath);
}

// Fixed-nonce (192,7) solve timing, for either solver Zero ships.
//
// SOLVE_TIMING_SOLVER=default (or unset) -> EhOptimisedSolve, the `default`
// solver. SOLVE_TIMING_SOLVER=tromp -> the vendored solver in src/pow/tromp,
// which contrib/conf-templates/prod.conf selects by default. Both arms run the
// same nonce sequence through the same timing and verification code, so the
// only difference is the solver (see contrib/perf/equ/METHOD.md S3.2f).
//
// The RPC benchmark
// (`zcbenchmark solveequihash`) draws a RANDOM nonce per trial
// (`src/zcbenchmarks.cpp`, randombytes_buf), so trials differ in how much work
// they contain and cannot be paired across builds. This case walks a FIXED
// nonce sequence, so run A and run B solve identical work and the difference
// is attributable to the code under test.
//
// Opt-in (each solve is ~30-70 s):
//   SOLVE_TIMING_1927=4 ./src/test/test_bitcoin \
//     --run_test=equihash_tests/solver_timing_192_7
//
// Optional: SOLVE_TIMING_TSV=<path> appends one row per nonce.
// Optional: SOLVE_TIMING_DUMP=<path> writes the solution SET, for diffing two
// solvers or two builds (order-independent).
//
// Build with -DPERF_PROBE to add solver diagnostics: leaf-generation time and
// share, and the accumulated xfull/bfull/hfull drop counters. Off by default --
// these are investigation aids, not part of the timing contract.
// Emits nsols per nonce as well as seconds -- a "speedup" that drops solutions
// is a loss in Sol/s, so the count travels with the time.
BOOST_AUTO_TEST_CASE(solver_timing_192_7) {
    const char* nEnv = getenv("SOLVE_TIMING_1927");
    if (nEnv == nullptr) {
        return;  // opt-in only
    }
    const int trials = atoi(nEnv);
    BOOST_REQUIRE_MESSAGE(trials > 0, "SOLVE_TIMING_1927 must be a positive count");

    SelectParams(CBaseChainParams::MAIN);
    const Consensus::Params& consensus = Params().GetConsensus();
    const unsigned int n = consensus.nEquihashN;
    const unsigned int k = consensus.nEquihashK;
    BOOST_REQUIRE_EQUAL(n, 192u);
    BOOST_REQUIRE_EQUAL(k, 7u);
    const size_t cBitLen = n / (k + 1);

    const char* solverEnv = getenv("SOLVE_TIMING_SOLVER");
    const std::string solverName = (solverEnv == nullptr) ? "default" : solverEnv;
    BOOST_REQUIRE_MESSAGE(solverName == "default" || solverName == "tromp",
                          "SOLVE_TIMING_SOLVER must be 'default' or 'tromp'");
    const bool useTromp = (solverName == "tromp");
    BOOST_TEST_MESSAGE("solver " << solverName);

    const char* dumpPath = getenv("SOLVE_TIMING_DUMP");
    std::ofstream dump;
    if (dumpPath != nullptr) {
        dump.open(dumpPath);
        BOOST_REQUIRE_MESSAGE(dump.good(), "cannot open SOLVE_TIMING_DUMP path");
    }

    const char* tsvPath = getenv("SOLVE_TIMING_TSV");
    std::ofstream tsv;
    if (tsvPath != nullptr) {
        tsv.open(tsvPath, std::ios::app);
        BOOST_REQUIRE_MESSAGE(tsv.good(), "cannot open SOLVE_TIMING_TSV path");
    }

    for (int t = 0; t < trials; t++) {
        // Fixed, reproducible nonce: trial index in an otherwise zero uint256.
        // Same sequence every run, so runs are directly comparable.
        CBlockHeader hdr = Params().GenesisBlock().GetBlockHeader();
        uint256 nonce;
        nonce.begin()[0] = (unsigned char)(t & 0xff);
        nonce.begin()[1] = (unsigned char)((t >> 8) & 0xff);

        // state built by the shared helper below
        CEquihashInput I{hdr};
        CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
        ss << I;
        ss << nonce;
        eh_HashState state = EhPrefixState(n, k, (unsigned char*)&ss[0], ss.size());

        std::set<std::vector<uint32_t>> sols;
        size_t rawSols = 0;      // solutions emitted before de-duplication
#ifdef PERF_PROBE
        double genSecs = -1.0;   // tromp only: time in digit0 (leaf generation)
#endif
        int64_t t0 = GetTimeMicros();
        if (useTromp) {
            // Driver lifted verbatim from miner.cpp so this measures the code
            // path a miner actually runs, not a reimplementation of it.
            equi eq(1);                       // single-threaded, as miner.cpp does
            eq.setstate(state.get());              // the SAME state object as the default arm
            // equi's constructor does not initialise xfull/hfull/bfull; only the
            // threaded worker (equi_miner.h:585) resets them. Zero them here so
            // a single-threaded caller never reads uninitialised memory.
            eq.xfull = eq.bfull = eq.hfull = 0;
#ifdef PERF_PROBE
            // Diagnostic only. genSecs isolates leaf generation (all the
            // blake2b) from the merge rounds; sumX/sumB/sumH accumulate the
            // drop counters that are otherwise reset and discarded per round:
            // xfull = xhash list (XFULL) overflow, bfull = bucket (NSLOTS)
            // overflow, hfull = duplicate-hash rejects. Nonzero xfull/bfull
            // mean pairs were dropped and solutions may be lost.
            u32 sumX = 0, sumB = 0, sumH = 0;
            const int64_t g0 = GetTimeMicros();
#endif
            eq.digit0(0);
#ifdef PERF_PROBE
            const int64_t g1 = GetTimeMicros();
            genSecs = (g1 - g0) / 1000000.0;
            sumX += eq.xfull; sumB += eq.bfull; sumH += eq.hfull;
#endif
            eq.xfull = eq.bfull = eq.hfull = 0;
            for (u32 r = 1; r < WK; r++) {
                (r & 1) ? eq.digitodd(r, 0) : eq.digiteven(r, 0);
#ifdef PERF_PROBE
                sumX += eq.xfull; sumB += eq.bfull; sumH += eq.hfull;
#endif
                eq.xfull = eq.bfull = eq.hfull = 0;
            }
            eq.digitK(0);
#ifdef PERF_PROBE
            sumX += eq.xfull; sumB += eq.bfull; sumH += eq.hfull;
            BOOST_TEST_MESSAGE("  tromp drops: xfull=" << sumX
                               << " bfull=" << sumB << " hfull=" << sumH);
#endif
            rawSols = eq.nsols;
            for (size_t si = 0; si < eq.nsols; si++) {
                std::vector<eh_index> idx(PROOFSIZE);
                for (size_t i = 0; i < PROOFSIZE; i++) {
                    idx[i] = eq.sols[si][i];
                }
                // DIGITBITS == n/(k+1) == cBitLen, so the encoding matches the
                // default arm exactly and the two solution sets are comparable.
                sols.insert(GetIndicesFromMinimal(GetMinimalFromIndices(idx, cBitLen), cBitLen));
            }
        } else {
            EhOptimisedSolveUncancellable(n, k, state, [&](std::vector<unsigned char> soln) {
                rawSols++;
                sols.insert(GetIndicesFromMinimal(soln, cBitLen));
                return false;  // collect every solution
            });
        }
        int64_t t1 = GetTimeMicros();
        const double secs = (t1 - t0) / 1000000.0;

        // tromp stores at most MAXSOLS (8) solutions and silently discards the
        // rest. Observed counts at (192,7) are 2-5, so 7 or 8 is already
        // suspicious and 8 may mean the cap truncated the set -- which would
        // make the two arms incomparable rather than merely different.
        if (useTromp && rawSols >= 7) {
            BOOST_TEST_MESSAGE("WARNING: nonce " << t << " emitted " << rawSols
                               << " solutions; MAXSOLS is 8, so the set may be"
                               " truncated and this nonce is not comparable");
        }

        // Every solution must verify: a faster solver emitting garbage is not
        // faster. V1 inside the timing loop so a bad number cannot be recorded.
        for (const auto& idx : sols) {
            std::vector<eh_index> ehidx(idx.begin(), idx.end());
            bool ok = false;
            EhIsValidSolution(n, k, state, GetMinimalFromIndices(ehidx, cBitLen), ok);
            BOOST_CHECK_MESSAGE(ok, "solver emitted a solution that does not verify");
        }

        BOOST_TEST_MESSAGE("solver " << solverName << " nonce " << t
                           << " secs " << secs << " nsols " << sols.size()
                           << " raw " << rawSols
#ifdef PERF_PROBE
                           << (genSecs >= 0 ? " gen " + std::to_string(genSecs)
                                              + " genpct " + std::to_string(100.0*genSecs/secs)
                                            : "")
#endif
                           );
        if (tsv.is_open()) {
            tsv << solverName << "\t" << t << "\t" << secs << "\t"
                << sols.size() << "\t" << rawSols << "\n";
            tsv.flush();
        }
        // Dump the solution SET so the two solvers can be diffed directly.
        // Order-independent: sols is a std::set of sorted index vectors.
        if (dump.is_open()) {
            for (const auto& idx : sols) {
                dump << t;
                for (uint32_t v : idx) dump << " " << v;
                dump << "\n";
            }
            dump.flush();
        }
    }
    if (tsv.is_open()) tsv.close();
    if (dump.is_open()) dump.close();
}

// Vendored tromp solver: structural invariants, ALWAYS ON.
//
// Zero ships two solvers and contrib/conf-templates/prod.conf selects tromp,
// but every other case in this file exercises only EhBasicSolve and
// EhOptimisedSolve. A change under src/pow/tromp/ passed the entire suite
// while being unvalidated against the solver a miner actually runs.
//
// tromp is compiled for (192,7) only (src/pow/tromp/equi.h), and one solve is
// ~9 s, so a full cross-solver differential cannot run by default. That gate
// is solver_timing_192_7 with SOLVE_TIMING_DUMP, diffed between
// SOLVE_TIMING_SOLVER=default and =tromp (contrib/perf/equ/METHOD.md S3.2f).
//
// What this case pins cheaply are the compile-time invariants that a tuning
// change (RESTBITS, tag width, slot type) can silently violate -- each of
// which corrupts results rather than failing to build.
BOOST_AUTO_TEST_CASE(tromp_solver_invariants) {
#ifdef ENABLE_MINING
    // 1. The tag must fit its storage. Exceeding this silently truncates the
    //    bucket id, so reconstruction returns wrong indices.
    BOOST_CHECK_MESSAGE(BUCKBITS + 2 * SLOTBITS <= 32,
                        "tromp tree tag exceeds 32 bits: "
                        "BUCKBITS + 2*SLOTBITS must fit u32 bid_s0_s1");

    // 2. Parameters must match consensus. A mismatch means the miner solves a
    //    different problem than the chain validates.
    SelectParams(CBaseChainParams::MAIN);
    const Consensus::Params& consensus = Params().GetConsensus();
    BOOST_CHECK_EQUAL((unsigned int)WN, consensus.nEquihashN);
    BOOST_CHECK_EQUAL((unsigned int)WK, consensus.nEquihashK);

    // 3. PROOFSIZE must equal 2^k: it sizes the index vector miner.cpp copies
    //    out of eq.sols[], so a mismatch reads past the end or truncates.
    BOOST_CHECK_EQUAL((size_t)PROOFSIZE, (size_t)1 << WK);

    // 4. DIGITBITS is the encoding width miner.cpp passes to
    //    GetMinimalFromIndices; it must equal the consensus collision length
    //    or emitted solutions are encoded wrongly.
    BOOST_CHECK_EQUAL((size_t)DIGITBITS,
                      (size_t)(consensus.nEquihashN / (consensus.nEquihashK + 1)));

    // 5. Bucket capacity must exceed the expected occupancy by a real margin.
    //    NSLOTS below the mean guarantees systematic row loss.
    const double expected_rows_per_bucket = (double)(1ULL << (DIGITBITS + 1)) / NBUCKETS;
    BOOST_CHECK_MESSAGE((double)NSLOTS > expected_rows_per_bucket,
                        "NSLOTS below expected bucket occupancy: rows will be dropped");
#endif
}

BOOST_AUTO_TEST_CASE(solver_testvectors_48_5) {
    SelectParams(CBaseChainParams::REGTEST);
    const Consensus::Params& consensus = Params().GetConsensus();
    const unsigned int n = consensus.nEquihashN;
    const unsigned int k = consensus.nEquihashK;
    BOOST_REQUIRE_EQUAL(n, 48u);
    BOOST_REQUIRE_EQUAL(k, 5u);
    const size_t cBitLen = n / (k + 1);
    CBlockHeader hdr = Params().GenesisBlock().GetBlockHeader();

    auto init_state = [&]() {
        CEquihashInput I{hdr};
        CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
        ss << I;
        ss << hdr.nNonce;
        return EhPrefixState(n, k, (unsigned char*)&ss[0], ss.size());
    };

    eh_HashState state_basic = init_state();
    std::set<std::vector<uint32_t>> basic;
    EhBasicSolveUncancellable(n, k, state_basic, [&](std::vector<unsigned char> soln) {
        basic.insert(GetIndicesFromMinimal(soln, cBitLen));
        return false;
    });
    BOOST_REQUIRE_MESSAGE(!basic.empty(), "BasicSolve found no (48,5) solutions on regtest genesis");

    eh_HashState state_opt = init_state();
    std::set<std::vector<uint32_t>> opt;
    EhOptimisedSolveUncancellable(n, k, state_opt, [&](std::vector<unsigned char> soln) {
        opt.insert(GetIndicesFromMinimal(soln, cBitLen));
        return false;
    });
    BOOST_CHECK(basic == opt);

    // Genesis solution must be among solver outputs
    std::vector<eh_index> genesis_idx = GetIndicesFromMinimal(hdr.nSolution, cBitLen);
    std::vector<uint32_t> genesis_u(genesis_idx.begin(), genesis_idx.end());
    BOOST_CHECK(basic.count(genesis_u) == 1);

    if (getenv("DUMP_48_5") != nullptr) {
        std::cerr << "cpp_nsols " << basic.size() << "\n";
        for (const auto& idx : basic) {
            std::cerr << "cpp";
            for (uint32_t v : idx) {
                std::cerr << " " << v;
            }
            std::cerr << "\n";
        }
        std::cerr << "cpp_genesis";
        for (uint32_t v : genesis_u) {
            std::cerr << " " << v;
        }
        std::cerr << "\n";
    }

    eh_HashState state_v = init_state();
    for (const auto& idx : basic) {
        BOOST_REQUIRE_EQUAL(idx.size(), 32u);
        bool isValid = false;
        EhIsValidSolution(n, k, state_v, GetMinimalFromIndices(idx, cBitLen), isValid);
        BOOST_CHECK(isValid);
    }
    SelectParams(CBaseChainParams::MAIN);
}
#endif

BOOST_AUTO_TEST_SUITE_END()
