name: Zero Linux CI

on:
  pull_request:
  push:
  schedule:
    - cron: '0 19 * * *'

jobs:

  linux-build:
    name: Linux Build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (Linux)

        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update  # prevents repo404 errors on apt-remove below
          sudo apt-get install \
              build-essential pkg-config libc6-dev m4 g++-multilib \
              autoconf libtool ncurses-dev unzip git python3 python3-zmq python-is-python3 \
              zlib1g-dev wget bsdmainutils automake cmake curl
          ./zcutil/fetch-params.sh

      - name: Build (Linux)
        run: |
          ./zcutil/build.sh -j$(nproc)
          tar -czvf zero-linux.tar.gz src/zerod src/zero-cli
          
      - name: Upload zero-linux.tar.gz as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zero-linux
          path: ./zero-linux.tar.gz
